### ISSUE TITLE
Tabelki w MySQL

### ISSUE THREAD

**Issue by Wruczek** [grzegorz2047/SurvivalCG#4]
Link do tabelek nie działa.
Sugeruje dodanie kodu do repository na githubie.

**Comment by Wruczek** [comment]
Nevermind, znalazłem w #1
Przydałoby się zaktualizować link w readme

**Comment by grzegorz2047** [comment]
Najlepiej jakby generowane były automatycznie przez plugin xd Ale nie chciało mi się xd
